language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=py27-m1-drf3.0
    - TOX_ENV=py27-m1-drf3.1
    - TOX_ENV=py27-m1-drf3.2
    - TOX_ENV=py27-m2-drf3.0
    - TOX_ENV=py27-m2-drf3.1
    - TOX_ENV=py27-m2-drf3.2
    - TOX_ENV=py33-m1-drf3.0
    - TOX_ENV=py33-m1-drf3.1
    - TOX_ENV=py33-m1-drf3.2
    - TOX_ENV=py33-m2-drf3.0
    - TOX_ENV=py33-m2-drf3.1
    - TOX_ENV=py33-m2-drf3.2
    - TOX_ENV=py34-m1-drf3.0
    - TOX_ENV=py34-m1-drf3.1
    - TOX_ENV=py34-m1-drf3.2
    - TOX_ENV=py34-m2-drf3.0
    - TOX_ENV=py34-m2-drf3.1
    - TOX_ENV=py34-m2-drf3.2


matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
