language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

sudo: false

env:
  matrix:
    - DRF=3.4
    - DRF=3.6

matrix:
  fast_finish: true

install:
  - travis_retry pip install -U virtualenv tox tox-travis

script:
    - tox
