# Created by: Sloria for Django-rest-marshmallow python library
# Edited by: davidzwa
# Date: April 2020
# Python package

# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
- template: job--python-tox.yml@sloria
  parameters:
    toxenvs: [lint, py35, py36, py37, py38, docs]
    os: linux
- template: job--pypi-release.yml@sloria
  parameters:
    dependsOn:
      - tox_linux
